### ISSUE TITLE
New ITE it9135 firmwares.

### ISSUE THREAD

**Issue by dhead666** [OpenELEC/dvb-firmware#12]
Antti Palosaari, Linux Media Tree developer, shared new firmware for it9135 extracted from the Windows' driver .

I don't know if it is a good idea to update the firmwares without proper testing.

I opened this issue as a reminder for the developers, the place for further discussion is the forum.

My it9135 based devices are usually stable and work great with the older firmware.
The only issue I've encounter is specific to the Raspberry Pi, in which some it9135 based devices (and AF9035) are unstable and crashes while others (like the WandTV) are much better and doesn't crash.
(Although its related to the state of the Raspberry Pi usb driver it still worth to test)

http://blog.palosaari.fi/2014/02/linux-it9135-driver-firmwares.html

**Comment by chewitt** [comment]
I'm closing this due to elapsed time. Thanks.
