### ISSUE TITLE
add dvb-usb-teviis660.fw

### ISSUE THREAD

**Issue by polojoe** [OpenELEC/dvb-firmware#19]
please add latest drivers for tevii s660 tv box

http://www.tevii.com/Tevii_Product_20141204media_build_b7.tar.bz2.rar

**Comment by stefansaraev** [comment]
whi is this not a PR ?

**Comment by stefansaraev** [comment]
in the file your link. there is no firmware named dvb-usb-teviis660.fw
closing this.

**Comment by polojoe** [comment]
stefansaraev,

I uploaded firmware to polojoe/dvb-firmware
but have no idea how to do PR.
https://github.com/polojoe/dvb-firmware/commit/3ae0aebc6f9b10d201132d6b80aa57136657e924

**Comment by stefansaraev** [comment]
as said, this firmware is NOT used in mainline linux, neither in your media_build .tar you posted.
